import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/components/layout/ClientProviders";
import NavbarFooterWrapper from "@/components/layout/NavbarFooterWrapper";
import NavbarServer from "@/HomePage/Navbar-Server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sellsfie Customer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <ClientProviders>
          <NavbarFooterWrapper navbar={<NavbarServer />}>
            {children}
          </NavbarFooterWrapper>
        </ClientProviders>
      </body>
    </html>
  );
}
